[package]
name = "hashman-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.21.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.72" }
dirs = "4.0.0"
