[package]
name = "hashman-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.21.2"
dirs = "4.0.0"
env_logger = "0.9.0"
log = "0.4.14"

[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "benchmark"
harness = false